### ISSUE TITLE
Implement Objview in PyRad.

### ISSUE THREAD

**Issue by sariths** [gmischler/PyRad#2]
This is a space for questions,comments etc. about the script for Objview.

**Comment by gmischler** [comment]
Note that objview (or rather rad) already has options named -V and -N.

The -V also means "verbose", so we can use that and pass it on.

Since it's an interactive program, we don't really need a "do nothing" mode. 
This would be -n in rad and -N in my other scripts. But in this case we can just use -N for the number of CPUs for rad.

I don't remember ever getting glrad to work, so I'm not sure how we'r going to test this part.

**Comment by sariths** [comment]
Hi @gmischler , I just submitted a pull request for an alpha version of Objview. It isn't nearly as complicated as I thought it was going to be. I have never gotten glard to work either. I have a Linux-Ubuntu system with me. I will see if I can get this script to run on that.

**Comment by sariths** [comment]
@gmischler Just a quick update, I finally got around to testing the script on my Linux/Ubuntu 16.04 64-bit system. I tried most options except glrad and everything seems to work fine. Below is a screen-shot:
![screenshot from 2016-04-23 21-37-00](https://cloud.githubusercontent.com/assets/10361848/14765011/4b244bbc-099c-11e6-8512-d008ca875a5b.png)

I tried multiple ways to get GlRad to install but none of them seem to work. It does not appear to ship with the NREL Radiance release or get built from the head release. I read the cmake file and think that some of the required libraries aren't getting found. I am not aware of anyone using GlRad at present except for its mention in Axel Jacobs' tutorial on Radiance.
