### ISSUE TITLE
Implement objpict

### ISSUE THREAD

**Issue by sariths** [gmischler/PyRad#6]
Hi @gmischler ,

I started writing objpict and ran into a couple of issues. 
-  Piping doesn't seem to work with oconv. If you uncomment the call_two [here](https://github.com/sariths/PyRad/blob/master/scripts/objpict.py#L147-L159) and run you'd get an idea.
- Secondly, my views don't seem to be capturing the object correctly.

I am still working on this one as I haven't implemented the dry run and verbose options yet. So, the file is currently on my fork. Once I have made the correction I will send a pull request.

**Comment by gmischler** [comment]
Oconv needs to know that it's supposed to read from stdin. That's what the `'-'` argument does:
`octreeCmd = ['oconv', self.testRoom, '-']`

The Perl version ads a `-t .5 .5 .5` to the transform (alternatively you can set all `.5` values in the views to `0`). 

Btw: List comprehensions are often much more practical to use than the outdated `map()`.

**Comment by sariths** [comment]
That fixes it. 

Thanks for the tip about list comprehensions. I do use `dict` and `list` comprehensions but didn't really think about them from an efficiency perspective. I did some reading on that and it makes sense to employ comprehensions instead of map. Although I'd like to use them, I still haven't found excuses for using generators till now as all these wrapper type scripts don't seem to require them.

Since I didn't find them in your code, are you okay with me using lambdas? I tend to write a lot of code in PyQT for my assistantship work at my university and have gotten used to employing lambdas to pass additional variables to methods.eg. something like `self.btnSelectColorLowerMask.clicked.connect(lambda:self.spMaskSettingsActivated(False))` where the `..clicked.connect()` needs a callable object as input. I know that I could get the same thing done through `functools.partial` but it just seems like an overkill if lambdas can do the same for me. I have used them in a couple of places here to take shortcuts.

**Comment by gmischler** [comment]
Python has many advanced functional features (list comprehensions, generators, generator expressions, lambdas, etc.), each of which has its uses. That doesn't mean you **have** to use all of them, just take the one that solves the problem most easily.
I also don't see a need for generators very often, they are most helpful for creating largish sets of data on the fly (I have a reimplementation of `vwrays` that uses them).
My most common use of lamdas is also for "currying" argument values in callback functions as you describe. Using one for just three explicit applications of `os.path.join()` seems a bit of an overkill though, and doesn't really help to simplify the code.

**Comment by sariths** [comment]
@gmischler Thanks for you insights. If you are okay with it, I am also going to implement `Ltpict` and `Ltview` then send a combined pull request in the coming weeks. I was tinkering with the `objline` c-shell script yesterday on my windows machine and wasn't able to get the part with targa files to work. Do you think it's possible to implement objline in a windows environment? Although the c-shell script has been around for years, I haven't seen a windows compatible script anywhere.

**Comment by gmischler** [comment]
You're volunteering here, so anything you do happens at your own schedule. Of course I'm happy to see the full set of preview scripts implemented!

Ibjline.csh doesn't seem to handle any targa files. It produces "meta" files as output and "mgf" files as intermediate format.
The manpage gives an example of how to convert the result to an image via a targa file. Are you talking about this? Does meta2tga or one of the other programs mentioned there not work on Windows?

**Comment by sariths** [comment]
Hi @gmischler, I thought of letting you know about my intention of eventually getting to Ltpict and Ltview as I didn't know if you were planning to add those scripts from your end. 

Regarding, the targa files, I get a `fatal -cannot open file "c:\tmp\vchars.mta", mode "r"` error. I literally read between the lines of the obline csh script to check if the workflow works without any glitches. rad --> mga --> meta works fine but the conversion from meta to targa fails.

**Comment by gmischler** [comment]
@sariths, I've seen your previous announcement about ltpict and ltview. I'm not working on those myself.

Your error message comes from the command `pexpand`, which again gets invoked by both `plot4` (in the script) and `meta2tga` (not in the script).

The file "vchars.mta" is a meta file included with Radiance as a support file to be used by other meta files. It is installed in the "meta" subdirectory of the Radiance library. Well, at least if you have installed everything. I found the following explanation from Greg in the mailing list archives:
 http://radiance-online.org/pipermail/radiance-general/2015-October/011285.html
If that doesn't help, we'll have to check further.

**Comment by sariths** [comment]
I guess the meta subdirectory does not get shipped with the NREL x64 bit version that I got from [here](https://github.com/NREL/Radiance/releases/download/5.0.a.10/radiance-5.0.a.10-win64.exe). Thanks for pointing me to the root of the problem. 

I don't want to bother too many people with these hobby projects of mine as objline and the other scripts work fine on my linux machine. I have tried building Radiance on Windows with cmake with mixed results in the past. I saw some discussion on Scons in the last few weeks but haven't really wrapped my head around the concept. Perhaps the meta directory might get built if I go the Scons route. I think I will close this issue for now and ping you back in a few weeks with the new scripts.

**Comment by gmischler** [comment]
Those files don't get built. They get installed from the support file package `rad5R0supp.tar.gz` (or in `rad5R0all.tar.gz` as mentioned in Greg's reply).
If the NREL distribution does not include them, but includes the executables that require them, then that's obviously a bug that should get fixed. I'll ask Rob about it.

This may be a "hobby project" to you. To everybody else it simply means that you're contributing improvements to Radiance. It's perfectly acceptable to "bother" the other developers if you run into any difficulties doing that.

In case you didn't follow that discussion: Based on our mutual finding that we couldn't get glrad to work, I've asked Greg on the dev list about it. His response was to fix it, so that the full functionality of objview.py is now available on the platforms that support X11, including Linux. This fix should already be included in the latest NREL release 5.0.a.10 (other than Windows). Of course it's also in the HEAD source release, but not yet in the "official" source release.

Personally I think that the SCons system is easier to use and more reliable than CMake, but that may just be because I created it myself... It's disadvantage is that it doesn't currently build qtrvu. Also note that you'll need Visual Studio 2013 to build with SCons (the community edition is ok). Visual Studio 2015 currently still has a show-stopping bug in its libc, which Microsoft will hopefully fix with the upcoming "anniversary update" to Windows 10 this summer.
